///////////////////////////////////////////////////////////
//  WinCalculate.cs
//  Implementation of the Class WinCalculate
//  Generated by Enterprise Architect
//  Created on:      27-ÁùÔÂ-2012 16:49:55
//  Original author: Administrator
///////////////////////////////////////////////////////////




using System;
using System.Collections.Generic;
using TG.Package.Lottery.Win;
using TG.Package.Lottery.Base;
namespace TG.Package.Lottery
{
    public class WinCalculate
    {

        public WinCalculate()
        {

        }

        /// 
        /// <param name="pLotteryType"></param>
        /// <param name="pLottery"></param>
        public static List<WinDetail> GetWinResult(LotteryType pLotteryType, ILottery pLottery)
        {

            return null;
        }

    }//end WinCalculate

}//end namespace System